"use client";

import { ChangeEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Camera, LogOut, Mail, Pencil, Phone, UserRound } from "lucide-react";
import { BackLink } from "@/components/ui/back-link";
import { ProfilePreferences } from "@/components/profile/profile-preferences";

type Profile = { id: string; name: string; email: string; phone?: string };

export default function ProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [draft, setDraft] = useState<Profile | null>(null); const [photo, setPhoto] = useState(""); const [editing, setEditing] = useState(false); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { const raw = localStorage.getItem("flatfolks_user"); const savedPhoto = localStorage.getItem("flatfolks_profile_photo"); if (raw) { const user = JSON.parse(raw) as Profile; setProfile(user); setDraft(user); } if (savedPhoto) setPhoto(savedPhoto); }); return () => window.cancelAnimationFrame(frame); }, []);
  function uploadPhoto(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const image = String(reader.result); setPhoto(image); localStorage.setItem("flatfolks_profile_photo", image); window.dispatchEvent(new Event("flatfolks-profile-photo")); }; reader.readAsDataURL(file); }
  function update(field: keyof Profile, value: string) { setDraft((current) => current ? { ...current, [field]: value } : current); }
  function logout() {
    localStorage.removeItem("flatfolks_user");
    localStorage.removeItem("flatfolks_profile_photo");
    localStorage.removeItem("flatfolks_chat_requests");
    window.location.assign("/auth");
  }
  async function save() { if (!draft) return; setSaving(true); setMessage(""); try { const response = await fetch(`/api/users/${draft.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: draft.name, email: draft.email, phone: draft.phone }) }); const result = await response.json() as { user?: Profile; error?: string }; if (!response.ok || !result.user) throw new Error(result.error || "Could not update profile."); setProfile(result.user); setDraft(result.user); localStorage.setItem("flatfolks_user", JSON.stringify(result.user)); setEditing(false); setMessage("Profile updated successfully. Old details have been replaced."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update profile."); } finally { setSaving(false); } }
  if (!profile || !draft) return <div className="min-h-screen bg-slate-50 px-4 py-16"><div className="mx-auto max-w-xl rounded-3xl bg-white p-8 text-center shadow-sm"><h1 className="text-2xl font-bold">Please log in first</h1><Link href="/auth" className="mt-5 inline-block rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">Create account or log in</Link></div></div>;
  const fields = [["name", "Name", UserRound], ["email", "Email ID", Mail], ["phone", "Phone number", Phone]] as const;
  return <div className="min-h-screen bg-slate-50 px-4 py-10 sm:px-6"><div className="mx-auto max-w-3xl"><BackLink label="Back to home" /><div className="mt-5 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-32 bg-gradient-to-r from-blue-600 to-indigo-700" /><div className="px-6 pb-8 sm:px-10"><div className="-mt-16 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="relative h-28 w-28 overflow-hidden rounded-full border-4 border-white bg-blue-100 shadow">{photo ? <img src={photo} alt="Profile" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-blue-600"><UserRound className="h-12 w-12" /></div>}</div><label className="cursor-pointer rounded-xl border border-blue-200 bg-white px-4 py-2.5 text-sm font-semibold text-blue-600"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadPhoto} className="hidden" /><Camera className="mr-2 inline h-4 w-4" />Upload profile photo</label></div><div className="mt-5 flex items-start justify-between gap-3"><div><h1 className="text-3xl font-bold text-slate-900">{profile.name}</h1><p className="mt-1 text-sm text-slate-500">Your FlatFolks account details</p></div><div className="flex flex-wrap justify-end gap-2"><button onClick={() => { setEditing((value) => !value); setDraft(profile); setMessage(""); }} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Pencil className="h-4 w-4" />{editing ? "Cancel" : "Edit profile"}</button><button type="button" onClick={logout} className="flex items-center gap-2 rounded-xl border border-red-200 bg-white px-4 py-2.5 text-sm font-semibold text-red-600 hover:bg-red-50"><LogOut className="h-4 w-4" />Log out</button></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2">{fields.map(([key, label, Icon]) => <div key={key} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 text-blue-600"><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><small className="block text-xs text-slate-500">{label}</small>{editing ? <input value={draft[key] || ""} onChange={(event) => update(key, event.target.value)} className="mt-1 w-full border-b border-blue-300 bg-transparent text-sm font-semibold outline-none" /> : <b className="text-sm">{profile[key] || "Not added"}</b>}</span></div>)}</div>{editing && <button onClick={save} disabled={saving} className="mt-5 rounded-xl bg-emerald-500 px-5 py-3 text-sm font-semibold text-white disabled:opacity-70">{saving ? "Saving..." : "Save updated details"}</button>}{message && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<ProfilePreferences /></div></div></div></div>;
}
